name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-dark.svg?color_snake=%23A78BFA&color_dots=%232d3343,%2322D3EE,%237C3AED,%23A78BFA,%23F5F3FF
            dist/github-snake-light.svg?color_snake=%237C3AED&color_dots=%23EDE9FE,%2322D3EE,%237C3AED,%23A78BFA,%230A101F&palette=light

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
